configuration:
  - Debug

build_script:
  - ps: .\build.ps1

cache:
  - src\packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified